### ISSUE TITLE
Support redis/v8

### ISSUE THREAD

**Issue by polastre** [johnsto/go-passwordless#4]
This library uses `redis/v7` but `redis/v8` has been out for some time.

Here are the changes to move from v7 to v8.

To keep existing clients working, recommend creating a `v8` branch and I can pull request into that branch. Then clients can use
```
import (
    "github.com/johnsto/go-passwordless/v8"
)
```
or similar

See this branch for changes:
https://github.com/polastre/go-passwordless/tree/redis-v8

**Comment by johnsto** [comment]
Thanks for the PR! I'm considering how to resolve this - aligning this
package's version directly against the Redis package version feels wrong
to me, but versioning as v2 also feels excessive for what is essentially
just a maintenance update.

Thoughts welcomed though!

On February 25, 2021, alkaris ***@***.***> wrote:
> This library uses redis/v7 but redis/v8 has been out for some time.
>
> Here are the changes to move from v7 to v8.
>
> To keep existing clients working, recommend creating a v8 branch and I
> can pull request into that branch. Then clients can use
>
> import ( "github.com/johnsto/go-passwordless/v8" )
> or similar
>
> See this branch for changes:
>  <https://github.com/polastre/go-passwordless/tree/redis-v8>
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/johnsto/go-passwordless/issues/4>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AALZ74TSSSQQACADLOPMNTDTAXJUVANCNFSM4YFZNSMA>.

**Comment by polastre** [comment]
I don't have a good answer here. I think a `v2` strategy may make sense so that you don't break people using `redis/v7`, but you provide a forward path to those that have upgraded to `redis/v8`. And probably set a EOL date for supporting `redis/v7` so you aren't tied to it forever.

**Comment by johnsto** [comment]
@polastre Apologies for taking so so so long to get to this! I've pushed a v2 which not only has multiple fixes, but module upgrades including moving to `redis/v8`.

**Comment by polastre** [comment]
Awesome! Thanks so much @johnsto!
